from pathlib import Path
from SCons.Script import COMMAND_LINE_TARGETS


UPLOAD_TARGETS = {"upload", "program"}
ENV_PATH = Path(".env")
HEADER_PATH = Path("src/generated_config.h")

DEFAULTS = {
    "WIFI_SSID": "YOUR_WIFI_SSID",
    "WIFI_PASSWORD": "YOUR_WIFI_PASSWORD",
    "WEATHER_LATITUDE": "-33.8688",
    "WEATHER_LONGITUDE": "151.2093",
    "WEATHER_TIMEZONE": "Australia/Sydney",
}


def parse_env(path):
    values = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value

    return values


def escape_cpp(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def write_header(values):
    HEADER_PATH.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by scripts/generate_config.py from .env.",
                "// Do not edit this file directly.",
                f'constexpr const char* kWifiSsid = "{escape_cpp(values["WIFI_SSID"])}";',
                f'constexpr const char* kWifiPassword = "{escape_cpp(values["WIFI_PASSWORD"])}";',
                f'constexpr const char* kWeatherLatitude = "{escape_cpp(values["WEATHER_LATITUDE"])}";',
                f'constexpr const char* kWeatherLongitude = "{escape_cpp(values["WEATHER_LONGITUDE"])}";',
                f'constexpr const char* kWeatherTimezone = "{escape_cpp(values["WEATHER_TIMEZONE"])}";',
                "",
            ]
        ),
        encoding="utf-8",
    )


values = DEFAULTS | parse_env(ENV_PATH)
write_header(values)

if UPLOAD_TARGETS.intersection(COMMAND_LINE_TARGETS):
    missing = []
    if values["WIFI_SSID"] in ("", DEFAULTS["WIFI_SSID"]):
        missing.append("WIFI_SSID")
    if values["WIFI_PASSWORD"] in ("", DEFAULTS["WIFI_PASSWORD"]):
        missing.append("WIFI_PASSWORD")

    if missing:
        print()
        print("Wi-Fi credentials are missing from .env.")
        print("Copy .env.example to .env and set WIFI_SSID and WIFI_PASSWORD before uploading.")
        print("This guard only blocks upload; pio run still works for compile checks.")
        print()
        raise SystemExit(1)
